# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regius < Formula
  desc "Regius CLI tool for web application development"
  homepage "https://github.com/hbarral/regius"
  version "1.10.1"

  on_macos do
    on_intel do
      url "https://github.com/hbarral/regius/releases/download/v1.10.1/regius_Darwin_x86_64.tar.gz"
      sha256 "a7d6c53cfe9644858cf039940c037a87335e2a4d51db53bd29bebe3b7e35c22c"

      def install
        bin.install "regius"
      end
    end
    on_arm do
      url "https://github.com/hbarral/regius/releases/download/v1.10.1/regius_Darwin_arm64.tar.gz"
      sha256 "fb67ceb9243c60f630cd92008b4fdcca8c847dd7f40562d3528a8750455a5422"

      def install
        bin.install "regius"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hbarral/regius/releases/download/v1.10.1/regius_Linux_x86_64.tar.gz"
        sha256 "c08808d0f19a3fca21cbff8ca20fc46020505f9912cb47dbe69bbb6dd157af52"

        def install
          bin.install "regius"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hbarral/regius/releases/download/v1.10.1/regius_Linux_arm64.tar.gz"
        sha256 "91c066f1d9dc6b3fc70d46d171783e47b0f0d1aaf8060965b89daaac862c4238"

        def install
          bin.install "regius"
        end
      end
    end
  end
end
